name: run c file

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile C file
      run: gcc -o test test.c

    - name: Run C file
      run: ./test

  windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download MinGW installer
      run: |
        curl -LO http://prdownloads.sourceforge.net/mingw/installer/mingw-get-setup.exe
        
    - name: Wait for 10 seconds
      run: sleep 10

    - name: Install MinGW
      run: |
        mingw-get-setup.exe /silent

    - name: Install GCC
      run: |
        mingw-get install gcc
        mingw-get install mingw32-make

    - name: Add MinGW to PATH
      run: setx PATH "%PATH%;C:\MinGW\bin"

    - name: Compile C file
      run: gcc -o test.exe src/test.c

    - name: Run C file
      run: .\test.exe